blueprint:
  name: Todo → Repeating Notifications
  description: Notify selected mobile devices on todo creation and at a configurable interval until acknowledged.
  domain: automation

  input:
    todo_list:
      name: Todo list
      selector:
        entity:
          domain: todo

    mobile_devices:
      name: Mobile devices
      description: Devices to notify
      selector:
        device:
          integration: mobile_app
          multiple: true

    interval:
      name: Notification interval (minutes)
      default: 15
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          step: 1

mode: single

trigger:
  - platform: event
    event_type: todo_item_added
    event_data:
      entity_id: !input todo_list

  - platform: time_pattern
    minutes: "/1"

variables:
  todo_entity: !input todo_list
  interval_minutes: !input interval

  # Map device IDs → notify services
  notify_services: >
    {% set services = [] %}
    {% for d in !input mobile_devices %}
      {% set device = device_attr(d, 'name') | lower | replace(' ', '_') %}
      {% set services = services + ['notify.mobile_app_' ~ device] %}
    {% endfor %}
    {{ services }}

action:
  - variables:
      items: "{{ state_attr(todo_entity, 'items') or [] }}"

  - repeat:
      for_each: >
        {{ items | selectattr('status', 'eq', 'needs_action') | list }}
      sequence:
        - condition: template
          value_template: >
            {% set created = as_datetime(repeat.item.created) %}
            {% set interval = interval_minutes | int %}
            {% set elapsed = (now() - created).total_seconds() %}
            {{ elapsed >= 0 and (elapsed // 60) % interval == 0 }}

        - repeat:
            for_each: "{{ notify_services }}"
            sequence:
              - service: "{{ repeat.item }}"
                data:
                  title: "{{ repeat.parent.item.summary }}"
                  message: "{{ repeat.parent.item.summary }}"
                  data:
                    tag: "todo_{{ repeat.parent.item.id }}"
                    actions:
                      - action: ACK_TODO
                        title: Acknowledge
                        data:
                          todo_id: "{{ repeat.parent.item.id }}"
